# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build nba-node`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t nba-node`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system nba-node && \
          adduser --system -G nba-node nba-node

COPY dist/nba-node nba-node
RUN chown -R nba-node:nba-node .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix nba-node --omit=dev -f install

CMD [ "node", "nba-node" ]
