# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build .`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t .`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system . && \
          adduser --system -G . .

COPY dist .
RUN chown -R .:. .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix . --omit=dev -f install

CMD [ "node", "." ]
